### ISSUE TITLE
windowsで本サイトを見た時に表示色がかなり濃くなる

### ISSUE THREAD

**Issue by RouxRhett** [RouxRhett/Ders#17]
## 概要
Windowsマシンのクロームで本サイトを確認した際に想定とは異なった色に感じた。

## 本修正に必要な追加情報
- mac,windowsで表示させた際の各要素のカラーコード

## 備考
app/assets/stylesheets/application.scss にてカラーコードを16進数で書いているところとARGBで書いているところがある。
```css
/* RGBAで指定 */
.top {
  background-color: rgba(1,194,178,0.48);
}

/* 16進数で指定 */
.navbar {
  background-color: #00a497;
}
```
